# Google Sheets
GOOGLE_SHEET_URL = "YOUR_SPREADSHEET_URL"

# OpenAI
OPENAI_API_KEY = "YOUR_OPENAI_API_KEY"
CUSTOM_MODEL = "YOUR_CUSTOM_GPT_MODEL"

# Translator
TRANSLATE_API_KEY = "YOUR_TRANSLATE_API_KEY"

# LINE
LINE_TOKEN = "YOUR_LINE_TOKEN"